# Configurations for arm prefixes used in gazebo launches
left:
  position:
    x: 0.0369
    y: 0.05018
    z: 1.0
    roll: -0.89334809
    pitch: -0.17456074
    yaw: -0.46334506
  controller: "joint_impedance_example_controller"
right:
  position:
    x: 0.0369
    y: -0.05018
    z: 1.0
    roll: 0.89334809
    pitch: -0.17456074
    yaw: 0.46334506
  controller: "joint_impedance_example_controller"
"":
  position:
    x: 0.0
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  controller: "mobile_cartesian_velocity_with_ik_example_controller"